### ISSUE TITLE
Switch to Spring Boot 2.4

### ISSUE THREAD

**Issue by MartinX3** [FAForever/gw-backend#21]
Switch the codebase to Spring Boot 2.0.4
Looks like the camunda spring boot project is ready for spring boot 2.0 by now (https://github.com/camunda/camunda-bpm-spring-boot-starter) so we could give it a try.

Subtasks:
- [x] Requires upgrade of Camunda to 7.9 (may require other dependencies to upgrade, otherwise I migrated a different project to 7.9 already, should be no problem)
- [x] Requires upgrade of Elide to 4.x

**Comment by MartinX3** [comment]
@Brutus5000 
Is that issue okay?

**Comment by Brutus5000** [comment]
Looks like the camunda spring boot project is ready for spring boot 2.0 by now (https://github.com/camunda/camunda-bpm-spring-boot-starter) so we could give it a try.

Subtasks:
- [x] Requires upgrade of Camunda to 7.9 (may require other dependencies to upgrade, otherwise I migrated a different project to 7.9 already, should be no problem)
- [x] Requires upgrade of Elide to 4.x

**Comment by MartinX3** [comment]
I updated the issue ticket.

**Comment by Brutus5000** [comment]
Unfortunately we are still blocked by one of our testing libraries: https://github.com/camunda/camunda-bpm-assert/issues/90.
As stated by Bernd Rücker it will come with Camunda 7.11 in May 2019.
No sense in doing migrations before that.

**Comment by Brutus5000** [comment]
Closed in c359a42d2d2feb87c152152f72a80c76d69b78a2
